# 当前配置文件适用于BAIDUYUN服务器在线使用
server:
  port: 9102
spring:
  application:
    name: coding-spring-test
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.159.160:3306/db_test?characterEncoding=utf8&useSSL=false
    username: coding
    password: ENC(8vaEdRT5WCBrXY9N/Z1qiQh7ISvwrd7Z)
# 整合mybatis
mybatis:
  # 数据持久化实体类路径
  type-aliases-package: com.lwk.coding.entity
  # xml文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
# 生产环境中，切记不要直接进行设置，可通过环境变量、命令行等形式进行设置
# jasypt.encryptor.password: lwk
logging:
  config: classpath:config/log4j2-baiduyun.xml
  level:
    # 打印SQL语句的日志级别是DEBUG，而打印SQL执行结果集的日志级别是TRACE
    com.lwk.coding.mapper: debug
